"""
Generate plain-English narratives from decomposition results.
"""

import os
import sys
from pathlib import Path
from typing import Dict, Optional
from datetime import datetime

from jinja2 import Environment
from dotenv import load_dotenv

sys.path.insert(0, str(Path(__file__).parent.parent))

from config.logging_config import setup_logger

load_dotenv()

logger = setup_logger(__name__)


def format_currency(value) -> str:
    """Format number as currency string."""
    if value is None:
        return "0.00"
    return f"{abs(float(value)):,.2f}"


# Create Jinja environment with custom filters
jinja_env = Environment()
jinja_env.filters['format_currency'] = format_currency
jinja_env.filters['abs'] = abs


# Narrative templates
METRIC_CHANGE_TEMPLATE = """
📊 **MetricPulse Alert: {{ metric_name }} {{ direction }}**

**{{ current_date }}** vs **{{ previous_date }}**

{{ metric_name }} {{ direction_verb }} **{{ change_pct }}%** (${{ previous_value | format_currency }} → ${{ current_value | format_currency }}), a change of **${{ change_value | format_currency }}**.

**Primary Driver:**
The {{ direction }} was primarily driven by **{{ top_driver.dimension | title }}** — specifically **{{ top_driver.segment }}**, which accounted for **{{ top_driver.contribution_pct | abs }}%** of the total change.

**Breakdown by Dimension:**
{% for dim_name, dim_data in dimensions.items() %}
- **{{ dim_name | title }}**: Top contributor was **{{ dim_data.top_segment }}** ({{ dim_data.top_contribution }}% of change)
{% endfor %}

---
*Generated by MetricPulse at {{ generated_at }}*
"""

SLACK_TEMPLATE = """
:chart_with_{{ 'upwards' if direction == 'increase' else 'downwards' }}_trend: *MetricPulse Alert*

*{{ metric_name }}* {{ direction_verb }} *{{ change_pct }}%* on {{ current_date }}

:mag: *Root Cause:* {{ top_driver.segment }} ({{ top_driver.dimension }}) drove {{ top_driver.contribution_pct | abs }}% of the change

:bar_chart: Breakdown:
{% for dim_name, dim_data in dimensions.items() %}• {{ dim_name | title }}: {{ dim_data.top_segment }} ({{ dim_data.top_contribution }}%)
{% endfor %}
"""

EMAIL_SUBJECT_TEMPLATE = """MetricPulse: {{ metric_name }} {{ direction }} {{ change_pct }}% on {{ current_date }}"""


def generate_narrative(
    decomposition_results: Dict,
    anomaly_info: Optional[Dict] = None,
    format_type: str = 'full'
) -> Dict[str, str]:
    """
    Generate narrative from decomposition results.
    
    Args:
        decomposition_results: Output from decomposer
        anomaly_info: Optional anomaly detection info
        format_type: 'full', 'slack', or 'email'
    
    Returns:
        Dictionary with formatted narratives
    """
    logger.info(f"Generating {format_type} narrative")
    
    # Extract key info
    current_date = decomposition_results['current_date']
    previous_date = decomposition_results['previous_date']
    metric_name = decomposition_results['metric'].replace('_', ' ').title()
    
    # Get first dimension's totals (they should all be the same)
    first_dim = list(decomposition_results['dimensions'].values())[0]
    current_value = first_dim['total_current']
    previous_value = first_dim['total_previous']
    change_value = first_dim['total_change']
    change_pct = first_dim['total_change_pct']
    
    # Determine direction
    direction = 'increase' if change_value > 0 else 'decrease'
    direction_verb = 'increased' if change_value > 0 else 'decreased'
    
    # Find top driver
    top_driver = None
    max_contribution = 0
    
    for dim_name, dim_data in decomposition_results['dimensions'].items():
        if 'error' in dim_data:
            continue
        for contributor in dim_data.get('top_contributors', []):
            if abs(contributor['contribution_pct']) > max_contribution:
                max_contribution = abs(contributor['contribution_pct'])
                top_driver = {
                    'dimension': dim_name,
                    'segment': contributor['segment'],
                    'contribution_pct': contributor['contribution_pct'],
                    'change': contributor['change']
                }
    
    # Build dimension summaries
    dimensions = {}
    for dim_name, dim_data in decomposition_results['dimensions'].items():
        if 'error' in dim_data:
            continue
        top = dim_data['top_contributors'][0] if dim_data.get('top_contributors') else None
        dimensions[dim_name] = {
            'top_segment': top['segment'] if top else 'N/A',
            'top_contribution': round(top['contribution_pct'], 1) if top else 0,
            'total_change_pct': dim_data['total_change_pct']
        }
    
    # Template context
    context = {
        'current_date': current_date,
        'previous_date': previous_date,
        'metric_name': metric_name,
        'current_value': current_value,
        'previous_value': previous_value,
        'change_value': change_value,
        'change_pct': abs(round(change_pct, 1)),
        'direction': direction,
        'direction_verb': direction_verb,
        'top_driver': top_driver,
        'dimensions': dimensions,
        'generated_at': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    }
    
    # Generate outputs
    outputs = {}
    
    # Full narrative
    full_template = jinja_env.from_string(METRIC_CHANGE_TEMPLATE)
    outputs['full'] = full_template.render(**context).strip()
    
    # Slack format
    slack_template = jinja_env.from_string(SLACK_TEMPLATE)
    outputs['slack'] = slack_template.render(**context).strip()
    
    # Email subject
    subject_template = jinja_env.from_string(EMAIL_SUBJECT_TEMPLATE)
    outputs['email_subject'] = subject_template.render(**context).strip()
    
    # Plain text summary (for logs/simple alerts)
    outputs['summary'] = (
        f"{metric_name} {direction_verb} {abs(round(change_pct, 1))}% on {current_date}. "
        f"Primary driver: {top_driver['segment']} ({top_driver['dimension']}) "
        f"contributed {abs(round(top_driver['contribution_pct'], 1))}% of the change."
    )
    
    logger.info(f"Generated narrative: {outputs['summary']}")
    
    return outputs


if __name__ == "__main__":
    # Test with decomposer
    from decomposition.decomposer import decompose_metric, get_comparison_dates
    
    logger.info("Testing narrative generation")
    
    try:
        # Get decomposition
        current_date, previous_date = get_comparison_dates()
        results = decompose_metric(current_date, previous_date)
        
        # Generate narratives
        narratives = generate_narrative(results)
        
        print("\n" + "=" * 60)
        print("FULL NARRATIVE")
        print("=" * 60)
        print(narratives['full'])
        
        print("\n" + "=" * 60)
        print("SLACK FORMAT")
        print("=" * 60)
        print(narratives['slack'])
        
        print("\n" + "=" * 60)
        print("EMAIL SUBJECT")
        print("=" * 60)
        print(narratives['email_subject'])
        
    except Exception as e:
        logger.error(f"Narrative generation failed: {e}")
        sys.exit(1)
